replicaCount: 1

image:
  repository: techiescamp/pomodoro
  tag: "8.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7070
  nodeport: 30111

configmap:
  mountpath: /app/config.js
  subpath: config.js

secretName: backend-secrets

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

## Network Policy
ingress:
  namespace: frontend
  appLabel: frontend
  port: 3000

egress:
  namespace: db
  appLabel: db
  port: 27017
